#!/usr/bin/env python

"""
Print a random password of 10 characters.
"""

from random import Random
import sys

# No i 1 o 0 l
ALPHABET = 'qwertyupasdfghjkzxcvbnmQWERTYUPASDFHJKLZXCVBNM2345789'

# 10 characters or the argument in parameter:
RESULT_LEN = int((sys.argv[1:2] or [10])[0])

def has_digit(sequence):
    """
    Return True if the sequence contains a digit (str).
    """

    return any(str(n) in sequence for n in range(10))

def password_generator():
    """
    Generates forever random sequence (string) of RESULT_LEN length.
    """

    while True:    
        yield "".join([Random().choice(ALPHABET) for i in range(RESULT_LEN)])

def password_with_digit_generator():
    """
    Generates forever random sequence (string) of RESULT_LEN length containing
    at least a digit.
    """

    for result in password_generator():
        if has_digit(result):
            yield result
    
# Generate a password containing at least a digit and send the
# output to stdout:
sys.stdout.write(next(iter(password_with_digit_generator())))
